# Generated by Django 4.1.1 on 2022-09-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_date', models.DateField(default='django.utils.timezone.now')),
                ('diary_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diary_duration', models.IntegerField(default=0)),
                ('diary_activity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_code', models.CharField(max_length=6)),
                ('exercise_name', models.CharField(max_length=20)),
                ('exercise_steps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.diary')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
    ]
